### ISSUE TITLE
Can't get rboot-sample to work

### ISSUE THREAD

**Issue by harryd100** [raburton/rboot-sample#1]
Hi, tried the rboot-example project but can't get it to work. Successfully compiled esptool2, rboot and the rboot-sample, copied the necessary rboot files to the project flashed an ESP-01. I have tried and ESP with 8Mb (no modification to the linker scripts) and 4Mb (modified second linker script to reflect 4Mb memory), but after flashing nothing happens on the serial port. I know the modules are fine (other SW works). What am i missing here. I have tried SDK 1.3.0 and 1.4.1, same results. I'm obviously doing something wrong, but because there are no errors, I can't figure out what. I really love the concept of rboot and want to use it in my future OTA projects. Please help

**Comment by raburton** [comment]
You should always get some output from the device, even just the bit before rBoot starts. If you are seeing nothing that suggests there is a problem connecting before rBoot and so you aren't seeing the rBoot messages. Are you connected with a baud rate of 74880 when the device starts? If it's all happening too fast for you to connect, try uncommenting the delay line in rboot.c to slow the boot down.
