### ISSUE TITLE
How to change the OTA Server by command

### ISSUE THREAD

**Issue by fvpalha** [raburton/rboot-sample#2]
Hi.

I think that the values:

```
#define OTA_HOST "192.168.7.5"
#define OTA_PORT 80
```

It should not be fixed.

How I can change this values by command?

**Comment by raburton** [comment]
The values are #defined so you can easily change them if you want to. This is just a sample, I can't see a scenario where you'd need to change this without it being acceptable to edit the file.

**Comment by fvpalha** [comment]
Thank you @raburton

**Comment by fvpalha** [comment]
[Define your own host and port by command](https://github.com/raburton/rboot-sample/pull/3)
