### ISSUE TITLE
wdt reset during upgrade process

### ISSUE THREAD

**Issue by gp-sudeep** [raburton/rboot-sample#5]
I am using this project with NON_OS_SDK 2.0. The code got compiled and most of it
is working. When i try to do a firmware upgrade it starts fetching the rom1.bin file but
the watchdog resets before completing the transfer from the server.

**Comment by raburton** [comment]
Do you know where it resets? The network receive code is all event based, so shouldn't be in any any bit of code long enough to cause a watchdog timeout. It doesn't happen for me, but if you identify the instruction stack at the point of the reset I might be able to figure out the problem.
