### ISSUE TITLE
server side : question

### ISSUE THREAD

**Issue by daffysub** [raburton/rboot-sample#6]
Hello Raburton,

I'm using a webserver run with node.js, when the upgrade start, I have an issue at the first reply and the download fail.

After investigation,  I have seen that the upgrade_recvcb function wait "Content-Length: " in the reply. but the response has "Transfer-Encoding: chunked" and no "Content-Length".

So, how do you proceed on server side to do an OTA with success?

Thank you in advance for your help.

**Comment by raburton** [comment]
The http client is quite simple, it doesn't support chunked encoding. Switching the protocol to http 1.0 will prevent the server using it. I meant to change that ages ago, but funnily enough I think you're the first person to actually hit this.
